### ISSUE TITLE
I am getting 'ArrayIndexOutOfBoundsException: 1 error with miraligner.

### ISSUE THREAD

**Issue by palbioinfor** [lpantano/seqbuster#21]
I am getting 'ArrayIndexOutOfBoundsException: 1 error with miraligner. Also sometimes it is "Javalangerror" too.

Can someone help me with that.
detail of the error is-

Format is not fasta, guessing tabular
species found
Go to mapping...
Mismatches: 1
Trimming: 3
Addition: 3
Species: hsa
Tue May 29 23:12:13 EDT 2018

Reading reads
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at miraligner.tools.getseq(tools.java:98)
	at miraligner.map.readseq(map.java:87)
	at miraligner.Main.main(Main.java:85)

**Comment by lpantano** [comment]
Hi,

Can you tell me wha Java version are you using?

As well, the right tool has to be downloaded from here:

https://github.com/lpantano/seqbuster/raw/miraligner/modules/miraligner/miraligner.jar <https://github.com/lpantano/seqbuster/raw/miraligner/modules/miraligner/miraligner.jar>

This version needs Java 8 to work.

Cheers

**Comment by palbioinfor** [comment]
Hey Thanks .
Yes I got the issue.
